version: '2'

services:
    db:
        image: 'postgres:latest'
        container_name: db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=shop-api

    backend:
        image: 'shop-api:latest'
        build:
            context: .
        container_name: app
        ports:
            -   "8081:8081"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        depends_on:
            -   db
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shop-api
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=postgres
            - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop